### ISSUE TITLE
Please add Retail Price to the GetReceivableCharges API

### ISSUE THREAD

**Issue by joeldeteves** [sherweb/Public-Apis#32]
We need to pull the Retail Price, not just the Cost Price so we can sync prices to our billing system.

Please add this to the GetReceivableCharges API.

Thank you,

**Comment by RaphCayou** [comment]
Hi Joel! We have just added this information inside the subscription! You may take a look at the pre-release changelog v1.0-beta06 [here](https://github.com/sherweb/Public-Apis/releases/tag/v1.0-beta06)

Here is also the [direct link](https://developers.sherweb.com/api-details#api=service-provider-api&operation=GetCustomerSubscriptions) to the documentation for the endpoint that now exposes the subscription fees.

I will close this issue, but don't hesitate to ask here or create a support request (the link is at the bottom of the main page of the documentation) if you have any questions.

Have a great day 🌞

**Comment by joeldeteves** [comment]
Awesome thank you, this will really help us with our billing integration!

Sent from my iPhone

On Oct 16, 2023, at 6:29 AM, Raphaël Cayouette ***@***.***> wrote:

﻿

Hi Joel! We have just added this information inside the subscription! You may take a look at the pre-release changelog v1.0-beta06 here<https://github.com/sherweb/Public-Apis/releases/tag/v1.0-beta06>

Here is also the direct link<https://developers.sherweb.com/api-details#api=service-provider-api&operation=GetCustomerSubscriptions> to the documentation for the endpoint that now exposes the subscription fees.

I will close this issue, but don't hesitate to ask here or create a support request (the link is at the bottom of the main page of the documentation) if you have any questions.

Have a great day 🌞
